package trikita.anvil.design;

import android.content.Context;
import android.content.res.ColorStateList;
import android.graphics.PorterDuff;
import android.graphics.Typeface;
import android.graphics.drawable.Drawable;
import android.support.design.internal.ForegroundLinearLayout;
import android.support.design.internal.NavigationMenuItemView;
import android.support.design.internal.NavigationMenuView;
import android.support.design.internal.ScrimInsetsFrameLayout;
import android.support.design.widget.AppBarLayout;
import android.support.design.widget.CollapsingToolbarLayout;
import android.support.design.widget.CoordinatorLayout;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.NavigationView;
import android.support.design.widget.TabItem;
import android.support.design.widget.TabLayout;
import android.support.design.widget.TextInputEditText;
import android.support.design.widget.TextInputLayout;
import android.support.v4.view.ViewPager;
import android.view.View;
import java.lang.Boolean;
import java.lang.CharSequence;
import java.lang.Float;
import java.lang.Integer;
import java.lang.Void;
import trikita.anvil.Anvil;
import trikita.anvil.BaseDSL;

/**
 * DSL for creating views and settings their attributes.
 * This file has been generated by {@code gradle generateDesignDSL}.
 * It contains views and their setters from the library design.
 * Please, don't edit it manually unless for debugging.
 */
public final class DesignDSL {
  public static ForegroundLinearLayout foregroundLinearLayout() {
    return BaseDSL.v(ForegroundLinearLayoutFactoryFunc.getInstance());
  }

  public static ForegroundLinearLayout foregroundLinearLayout(Anvil.Renderable r) {
    return BaseDSL.v(ForegroundLinearLayoutFactoryFunc.getInstance(), r);
  }

  public static NavigationMenuItemView navigationMenuItemView() {
    return BaseDSL.v(NavigationMenuItemViewFactoryFunc.getInstance());
  }

  public static NavigationMenuItemView navigationMenuItemView(Anvil.Renderable r) {
    return BaseDSL.v(NavigationMenuItemViewFactoryFunc.getInstance(), r);
  }

  public static NavigationMenuView navigationMenuView() {
    return BaseDSL.v(NavigationMenuViewFactoryFunc.getInstance());
  }

  public static NavigationMenuView navigationMenuView(Anvil.Renderable r) {
    return BaseDSL.v(NavigationMenuViewFactoryFunc.getInstance(), r);
  }

  public static ScrimInsetsFrameLayout scrimInsetsFrameLayout() {
    return BaseDSL.v(ScrimInsetsFrameLayoutFactoryFunc.getInstance());
  }

  public static ScrimInsetsFrameLayout scrimInsetsFrameLayout(Anvil.Renderable r) {
    return BaseDSL.v(ScrimInsetsFrameLayoutFactoryFunc.getInstance(), r);
  }

  public static AppBarLayout appBarLayout() {
    return BaseDSL.v(AppBarLayoutFactoryFunc.getInstance());
  }

  public static AppBarLayout appBarLayout(Anvil.Renderable r) {
    return BaseDSL.v(AppBarLayoutFactoryFunc.getInstance(), r);
  }

  public static CollapsingToolbarLayout collapsingToolbarLayout() {
    return BaseDSL.v(CollapsingToolbarLayoutFactoryFunc.getInstance());
  }

  public static CollapsingToolbarLayout collapsingToolbarLayout(Anvil.Renderable r) {
    return BaseDSL.v(CollapsingToolbarLayoutFactoryFunc.getInstance(), r);
  }

  public static CoordinatorLayout coordinatorLayout() {
    return BaseDSL.v(CoordinatorLayoutFactoryFunc.getInstance());
  }

  public static CoordinatorLayout coordinatorLayout(Anvil.Renderable r) {
    return BaseDSL.v(CoordinatorLayoutFactoryFunc.getInstance(), r);
  }

  public static FloatingActionButton floatingActionButton() {
    return BaseDSL.v(FloatingActionButtonFactoryFunc.getInstance());
  }

  public static FloatingActionButton floatingActionButton(Anvil.Renderable r) {
    return BaseDSL.v(FloatingActionButtonFactoryFunc.getInstance(), r);
  }

  public static NavigationView navigationView() {
    return BaseDSL.v(NavigationViewFactoryFunc.getInstance());
  }

  public static NavigationView navigationView(Anvil.Renderable r) {
    return BaseDSL.v(NavigationViewFactoryFunc.getInstance(), r);
  }

  public static TabItem tabItem() {
    return BaseDSL.v(TabItemFactoryFunc.getInstance());
  }

  public static TabItem tabItem(Anvil.Renderable r) {
    return BaseDSL.v(TabItemFactoryFunc.getInstance(), r);
  }

  public static TabLayout tabLayout() {
    return BaseDSL.v(TabLayoutFactoryFunc.getInstance());
  }

  public static TabLayout tabLayout(Anvil.Renderable r) {
    return BaseDSL.v(TabLayoutFactoryFunc.getInstance(), r);
  }

  public static TextInputEditText textInputEditText() {
    return BaseDSL.v(TextInputEditTextFactoryFunc.getInstance());
  }

  public static TextInputEditText textInputEditText(Anvil.Renderable r) {
    return BaseDSL.v(TextInputEditTextFactoryFunc.getInstance(), r);
  }

  public static TextInputLayout textInputLayout() {
    return BaseDSL.v(TextInputLayoutFactoryFunc.getInstance());
  }

  public static TextInputLayout textInputLayout(Anvil.Renderable r) {
    return BaseDSL.v(TextInputLayoutFactoryFunc.getInstance(), r);
  }

  public static Void backgroundTintList(ColorStateList arg) {
    return BaseDSL.attr(BackgroundTintListFunc9e5e0e4e.getInstance(), arg);
  }

  public static Void backgroundTintMode(PorterDuff.Mode arg) {
    return BaseDSL.attr(BackgroundTintModeFuncabb7a84e.getInstance(), arg);
  }

  public static Void checkable(boolean arg) {
    return BaseDSL.attr(CheckableFunc148d6054.getInstance(), arg);
  }

  public static Void checked(boolean arg) {
    return BaseDSL.attr(CheckedFunc148d6054.getInstance(), arg);
  }

  public static Void checkedItem(int arg) {
    return BaseDSL.attr(CheckedItemFunc8567756a.getInstance(), arg);
  }

  public static Void collapsedTitleGravity(int arg) {
    return BaseDSL.attr(CollapsedTitleGravityFunc8567756a.getInstance(), arg);
  }

  public static Void collapsedTitleTextAppearance(int arg) {
    return BaseDSL.attr(CollapsedTitleTextAppearanceFunc8567756a.getInstance(), arg);
  }

  public static Void collapsedTitleTextColor(int arg) {
    return BaseDSL.attr(CollapsedTitleTextColorFunc8567756a.getInstance(), arg);
  }

  public static Void collapsedTitleTypeface(Typeface arg) {
    return BaseDSL.attr(CollapsedTitleTypefaceFunc53b4afb.getInstance(), arg);
  }

  public static Void compatElevation(float arg) {
    return BaseDSL.attr(CompatElevationFunce0893188.getInstance(), arg);
  }

  public static Void contentScrim(Drawable arg) {
    return BaseDSL.attr(ContentScrimFuncfb47464a.getInstance(), arg);
  }

  public static Void contentScrimColor(int arg) {
    return BaseDSL.attr(ContentScrimColorFunc8567756a.getInstance(), arg);
  }

  public static Void contentScrimResource(int arg) {
    return BaseDSL.attr(ContentScrimResourceFunc8567756a.getInstance(), arg);
  }

  public static Void counterEnabled(boolean arg) {
    return BaseDSL.attr(CounterEnabledFunc148d6054.getInstance(), arg);
  }

  public static Void counterMaxLength(int arg) {
    return BaseDSL.attr(CounterMaxLengthFunc8567756a.getInstance(), arg);
  }

  public static Void error(CharSequence arg) {
    return BaseDSL.attr(ErrorFuncc0af808b.getInstance(), arg);
  }

  public static Void errorEnabled(boolean arg) {
    return BaseDSL.attr(ErrorEnabledFunc148d6054.getInstance(), arg);
  }

  public static Void expanded(boolean arg) {
    return BaseDSL.attr(ExpandedFunc148d6054.getInstance(), arg);
  }

  public static Void expandedTitleColor(int arg) {
    return BaseDSL.attr(ExpandedTitleColorFunc8567756a.getInstance(), arg);
  }

  public static Void expandedTitleGravity(int arg) {
    return BaseDSL.attr(ExpandedTitleGravityFunc8567756a.getInstance(), arg);
  }

  public static Void expandedTitleMarginBottom(int arg) {
    return BaseDSL.attr(ExpandedTitleMarginBottomFunc8567756a.getInstance(), arg);
  }

  public static Void expandedTitleMarginEnd(int arg) {
    return BaseDSL.attr(ExpandedTitleMarginEndFunc8567756a.getInstance(), arg);
  }

  public static Void expandedTitleMarginStart(int arg) {
    return BaseDSL.attr(ExpandedTitleMarginStartFunc8567756a.getInstance(), arg);
  }

  public static Void expandedTitleMarginTop(int arg) {
    return BaseDSL.attr(ExpandedTitleMarginTopFunc8567756a.getInstance(), arg);
  }

  public static Void expandedTitleTextAppearance(int arg) {
    return BaseDSL.attr(ExpandedTitleTextAppearanceFunc8567756a.getInstance(), arg);
  }

  public static Void expandedTitleTypeface(Typeface arg) {
    return BaseDSL.attr(ExpandedTitleTypefaceFunc53b4afb.getInstance(), arg);
  }

  public static Void foreground(Drawable arg) {
    return BaseDSL.attr(ForegroundFuncfb47464a.getInstance(), arg);
  }

  public static Void foregroundGravity(int arg) {
    return BaseDSL.attr(ForegroundGravityFunc8567756a.getInstance(), arg);
  }

  public static Void hint(CharSequence arg) {
    return BaseDSL.attr(HintFuncc0af808b.getInstance(), arg);
  }

  public static Void hintAnimationEnabled(boolean arg) {
    return BaseDSL.attr(HintAnimationEnabledFunc148d6054.getInstance(), arg);
  }

  public static Void hintEnabled(boolean arg) {
    return BaseDSL.attr(HintEnabledFunc148d6054.getInstance(), arg);
  }

  public static Void hintTextAppearance(int arg) {
    return BaseDSL.attr(HintTextAppearanceFunc8567756a.getInstance(), arg);
  }

  public static Void icon(Drawable arg) {
    return BaseDSL.attr(IconFuncfb47464a.getInstance(), arg);
  }

  public static Void itemBackground(Drawable arg) {
    return BaseDSL.attr(ItemBackgroundFuncfb47464a.getInstance(), arg);
  }

  public static Void itemBackgroundResource(int arg) {
    return BaseDSL.attr(ItemBackgroundResourceFunc8567756a.getInstance(), arg);
  }

  public static Void itemIconTintList(ColorStateList arg) {
    return BaseDSL.attr(ItemIconTintListFunc9e5e0e4e.getInstance(), arg);
  }

  public static Void itemTextAppearance(int arg) {
    return BaseDSL.attr(ItemTextAppearanceFunc8567756a.getInstance(), arg);
  }

  public static Void itemTextColor(ColorStateList arg) {
    return BaseDSL.attr(ItemTextColorFunc9e5e0e4e.getInstance(), arg);
  }

  public static Void navigationItemSelectedListener(NavigationView.OnNavigationItemSelectedListener arg) {
    return BaseDSL.attr(NavigationItemSelectedListenerFunc80db0872.getInstance(), arg);
  }

  public static Void onTabSelected(TabLayout.OnTabSelectedListener arg) {
    return BaseDSL.attr(OnTabSelectedFuncaa1c085e.getInstance(), arg);
  }

  public static Void rippleColor(int arg) {
    return BaseDSL.attr(RippleColorFunc8567756a.getInstance(), arg);
  }

  public static Void scrimsShown(boolean arg) {
    return BaseDSL.attr(ScrimsShownFunc148d6054.getInstance(), arg);
  }

  public static Void selectedTabIndicatorColor(int arg) {
    return BaseDSL.attr(SelectedTabIndicatorColorFunc8567756a.getInstance(), arg);
  }

  public static Void selectedTabIndicatorHeight(int arg) {
    return BaseDSL.attr(SelectedTabIndicatorHeightFunc8567756a.getInstance(), arg);
  }

  public static Void statusBarBackground(Drawable arg) {
    return BaseDSL.attr(StatusBarBackgroundFuncfb47464a.getInstance(), arg);
  }

  public static Void statusBarBackgroundColor(int arg) {
    return BaseDSL.attr(StatusBarBackgroundColorFunc8567756a.getInstance(), arg);
  }

  public static Void statusBarBackgroundResource(int arg) {
    return BaseDSL.attr(StatusBarBackgroundResourceFunc8567756a.getInstance(), arg);
  }

  public static Void statusBarScrim(Drawable arg) {
    return BaseDSL.attr(StatusBarScrimFuncfb47464a.getInstance(), arg);
  }

  public static Void statusBarScrimColor(int arg) {
    return BaseDSL.attr(StatusBarScrimColorFunc8567756a.getInstance(), arg);
  }

  public static Void statusBarScrimResource(int arg) {
    return BaseDSL.attr(StatusBarScrimResourceFunc8567756a.getInstance(), arg);
  }

  public static Void tabGravity(int arg) {
    return BaseDSL.attr(TabGravityFunc8567756a.getInstance(), arg);
  }

  public static Void tabMode(int arg) {
    return BaseDSL.attr(TabModeFunc8567756a.getInstance(), arg);
  }

  public static Void tabTextColors(ColorStateList arg) {
    return BaseDSL.attr(TabTextColorsFunc9e5e0e4e.getInstance(), arg);
  }

  public static Void targetElevation(float arg) {
    return BaseDSL.attr(TargetElevationFunce0893188.getInstance(), arg);
  }

  public static Void textColor(ColorStateList arg) {
    return BaseDSL.attr(TextColorFunc9e5e0e4e.getInstance(), arg);
  }

  public static Void title(CharSequence arg) {
    return BaseDSL.attr(TitleFuncc0af808b.getInstance(), arg);
  }

  public static Void titleEnabled(boolean arg) {
    return BaseDSL.attr(TitleEnabledFunc148d6054.getInstance(), arg);
  }

  public static Void typeface(Typeface arg) {
    return BaseDSL.attr(TypefaceFunc53b4afb.getInstance(), arg);
  }

  public static Void upWithViewPager(ViewPager arg) {
    return BaseDSL.attr(UpWithViewPagerFunc648eda47.getInstance(), arg);
  }

  public static Void useCompatPadding(boolean arg) {
    return BaseDSL.attr(UseCompatPaddingFunc148d6054.getInstance(), arg);
  }

  private static final class ForegroundLinearLayoutFactoryFunc implements Anvil.FactoryFunc<ForegroundLinearLayout> {
    private static ForegroundLinearLayoutFactoryFunc instance = null;

    public static ForegroundLinearLayoutFactoryFunc getInstance() {
      if(instance == null) {
        instance = new ForegroundLinearLayoutFactoryFunc();
      }
      return instance;
    }

    public ForegroundLinearLayout apply(Context c) {
      return new ForegroundLinearLayout(c);
    }
  }

  private static final class NavigationMenuItemViewFactoryFunc implements Anvil.FactoryFunc<NavigationMenuItemView> {
    private static NavigationMenuItemViewFactoryFunc instance = null;

    public static NavigationMenuItemViewFactoryFunc getInstance() {
      if(instance == null) {
        instance = new NavigationMenuItemViewFactoryFunc();
      }
      return instance;
    }

    public NavigationMenuItemView apply(Context c) {
      return new NavigationMenuItemView(c);
    }
  }

  private static final class NavigationMenuViewFactoryFunc implements Anvil.FactoryFunc<NavigationMenuView> {
    private static NavigationMenuViewFactoryFunc instance = null;

    public static NavigationMenuViewFactoryFunc getInstance() {
      if(instance == null) {
        instance = new NavigationMenuViewFactoryFunc();
      }
      return instance;
    }

    public NavigationMenuView apply(Context c) {
      return new NavigationMenuView(c);
    }
  }

  private static final class ScrimInsetsFrameLayoutFactoryFunc implements Anvil.FactoryFunc<ScrimInsetsFrameLayout> {
    private static ScrimInsetsFrameLayoutFactoryFunc instance = null;

    public static ScrimInsetsFrameLayoutFactoryFunc getInstance() {
      if(instance == null) {
        instance = new ScrimInsetsFrameLayoutFactoryFunc();
      }
      return instance;
    }

    public ScrimInsetsFrameLayout apply(Context c) {
      return new ScrimInsetsFrameLayout(c);
    }
  }

  private static final class AppBarLayoutFactoryFunc implements Anvil.FactoryFunc<AppBarLayout> {
    private static AppBarLayoutFactoryFunc instance = null;

    public static AppBarLayoutFactoryFunc getInstance() {
      if(instance == null) {
        instance = new AppBarLayoutFactoryFunc();
      }
      return instance;
    }

    public AppBarLayout apply(Context c) {
      return new AppBarLayout(c);
    }
  }

  private static final class CollapsingToolbarLayoutFactoryFunc implements Anvil.FactoryFunc<CollapsingToolbarLayout> {
    private static CollapsingToolbarLayoutFactoryFunc instance = null;

    public static CollapsingToolbarLayoutFactoryFunc getInstance() {
      if(instance == null) {
        instance = new CollapsingToolbarLayoutFactoryFunc();
      }
      return instance;
    }

    public CollapsingToolbarLayout apply(Context c) {
      return new CollapsingToolbarLayout(c);
    }
  }

  private static final class CoordinatorLayoutFactoryFunc implements Anvil.FactoryFunc<CoordinatorLayout> {
    private static CoordinatorLayoutFactoryFunc instance = null;

    public static CoordinatorLayoutFactoryFunc getInstance() {
      if(instance == null) {
        instance = new CoordinatorLayoutFactoryFunc();
      }
      return instance;
    }

    public CoordinatorLayout apply(Context c) {
      return new CoordinatorLayout(c);
    }
  }

  private static final class FloatingActionButtonFactoryFunc implements Anvil.FactoryFunc<FloatingActionButton> {
    private static FloatingActionButtonFactoryFunc instance = null;

    public static FloatingActionButtonFactoryFunc getInstance() {
      if(instance == null) {
        instance = new FloatingActionButtonFactoryFunc();
      }
      return instance;
    }

    public FloatingActionButton apply(Context c) {
      return new FloatingActionButton(c);
    }
  }

  private static final class NavigationViewFactoryFunc implements Anvil.FactoryFunc<NavigationView> {
    private static NavigationViewFactoryFunc instance = null;

    public static NavigationViewFactoryFunc getInstance() {
      if(instance == null) {
        instance = new NavigationViewFactoryFunc();
      }
      return instance;
    }

    public NavigationView apply(Context c) {
      return new NavigationView(c);
    }
  }

  private static final class TabItemFactoryFunc implements Anvil.FactoryFunc<TabItem> {
    private static TabItemFactoryFunc instance = null;

    public static TabItemFactoryFunc getInstance() {
      if(instance == null) {
        instance = new TabItemFactoryFunc();
      }
      return instance;
    }

    public TabItem apply(Context c) {
      return new TabItem(c);
    }
  }

  private static final class TabLayoutFactoryFunc implements Anvil.FactoryFunc<TabLayout> {
    private static TabLayoutFactoryFunc instance = null;

    public static TabLayoutFactoryFunc getInstance() {
      if(instance == null) {
        instance = new TabLayoutFactoryFunc();
      }
      return instance;
    }

    public TabLayout apply(Context c) {
      return new TabLayout(c);
    }
  }

  private static final class TextInputEditTextFactoryFunc implements Anvil.FactoryFunc<TextInputEditText> {
    private static TextInputEditTextFactoryFunc instance = null;

    public static TextInputEditTextFactoryFunc getInstance() {
      if(instance == null) {
        instance = new TextInputEditTextFactoryFunc();
      }
      return instance;
    }

    public TextInputEditText apply(Context c) {
      return new TextInputEditText(c);
    }
  }

  private static final class TextInputLayoutFactoryFunc implements Anvil.FactoryFunc<TextInputLayout> {
    private static TextInputLayoutFactoryFunc instance = null;

    public static TextInputLayoutFactoryFunc getInstance() {
      if(instance == null) {
        instance = new TextInputLayoutFactoryFunc();
      }
      return instance;
    }

    public TextInputLayout apply(Context c) {
      return new TextInputLayout(c);
    }
  }

  private static final class BackgroundTintListFunc9e5e0e4e implements Anvil.AttrFunc<ColorStateList> {
    private static BackgroundTintListFunc9e5e0e4e instance = null;

    public static BackgroundTintListFunc9e5e0e4e getInstance() {
      if(instance == null) {
        instance = new BackgroundTintListFunc9e5e0e4e();
      }
      return instance;
    }

    public void apply(View v, final ColorStateList arg, final ColorStateList old) {
      if (v instanceof FloatingActionButton) {
        ((FloatingActionButton) v).setBackgroundTintList(arg);
      }
    }
  }

  private static final class BackgroundTintModeFuncabb7a84e implements Anvil.AttrFunc<PorterDuff.Mode> {
    private static BackgroundTintModeFuncabb7a84e instance = null;

    public static BackgroundTintModeFuncabb7a84e getInstance() {
      if(instance == null) {
        instance = new BackgroundTintModeFuncabb7a84e();
      }
      return instance;
    }

    public void apply(View v, final PorterDuff.Mode arg, final PorterDuff.Mode old) {
      if (v instanceof FloatingActionButton) {
        ((FloatingActionButton) v).setBackgroundTintMode(arg);
      }
    }
  }

  private static final class CheckableFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    private static CheckableFunc148d6054 instance = null;

    public static CheckableFunc148d6054 getInstance() {
      if(instance == null) {
        instance = new CheckableFunc148d6054();
      }
      return instance;
    }

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof NavigationMenuItemView) {
        ((NavigationMenuItemView) v).setCheckable(arg);
      }
    }
  }

  private static final class CheckedFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    private static CheckedFunc148d6054 instance = null;

    public static CheckedFunc148d6054 getInstance() {
      if(instance == null) {
        instance = new CheckedFunc148d6054();
      }
      return instance;
    }

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof NavigationMenuItemView) {
        ((NavigationMenuItemView) v).setChecked(arg);
      }
    }
  }

  private static final class CheckedItemFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static CheckedItemFunc8567756a instance = null;

    public static CheckedItemFunc8567756a getInstance() {
      if(instance == null) {
        instance = new CheckedItemFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof NavigationView) {
        ((NavigationView) v).setCheckedItem(arg);
      }
    }
  }

  private static final class CollapsedTitleGravityFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static CollapsedTitleGravityFunc8567756a instance = null;

    public static CollapsedTitleGravityFunc8567756a getInstance() {
      if(instance == null) {
        instance = new CollapsedTitleGravityFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setCollapsedTitleGravity(arg);
      }
    }
  }

  private static final class CollapsedTitleTextAppearanceFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static CollapsedTitleTextAppearanceFunc8567756a instance = null;

    public static CollapsedTitleTextAppearanceFunc8567756a getInstance() {
      if(instance == null) {
        instance = new CollapsedTitleTextAppearanceFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setCollapsedTitleTextAppearance(arg);
      }
    }
  }

  private static final class CollapsedTitleTextColorFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static CollapsedTitleTextColorFunc8567756a instance = null;

    public static CollapsedTitleTextColorFunc8567756a getInstance() {
      if(instance == null) {
        instance = new CollapsedTitleTextColorFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setCollapsedTitleTextColor(arg);
      }
    }
  }

  private static final class CollapsedTitleTypefaceFunc53b4afb implements Anvil.AttrFunc<Typeface> {
    private static CollapsedTitleTypefaceFunc53b4afb instance = null;

    public static CollapsedTitleTypefaceFunc53b4afb getInstance() {
      if(instance == null) {
        instance = new CollapsedTitleTypefaceFunc53b4afb();
      }
      return instance;
    }

    public void apply(View v, final Typeface arg, final Typeface old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setCollapsedTitleTypeface(arg);
      }
    }
  }

  private static final class CompatElevationFunce0893188 implements Anvil.AttrFunc<Float> {
    private static CompatElevationFunce0893188 instance = null;

    public static CompatElevationFunce0893188 getInstance() {
      if(instance == null) {
        instance = new CompatElevationFunce0893188();
      }
      return instance;
    }

    public void apply(View v, final Float arg, final Float old) {
      if (v instanceof FloatingActionButton) {
        ((FloatingActionButton) v).setCompatElevation(arg);
      }
    }
  }

  private static final class ContentScrimFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    private static ContentScrimFuncfb47464a instance = null;

    public static ContentScrimFuncfb47464a getInstance() {
      if(instance == null) {
        instance = new ContentScrimFuncfb47464a();
      }
      return instance;
    }

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setContentScrim(arg);
      }
    }
  }

  private static final class ContentScrimColorFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static ContentScrimColorFunc8567756a instance = null;

    public static ContentScrimColorFunc8567756a getInstance() {
      if(instance == null) {
        instance = new ContentScrimColorFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setContentScrimColor(arg);
      }
    }
  }

  private static final class ContentScrimResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static ContentScrimResourceFunc8567756a instance = null;

    public static ContentScrimResourceFunc8567756a getInstance() {
      if(instance == null) {
        instance = new ContentScrimResourceFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setContentScrimResource(arg);
      }
    }
  }

  private static final class CounterEnabledFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    private static CounterEnabledFunc148d6054 instance = null;

    public static CounterEnabledFunc148d6054 getInstance() {
      if(instance == null) {
        instance = new CounterEnabledFunc148d6054();
      }
      return instance;
    }

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof TextInputLayout) {
        ((TextInputLayout) v).setCounterEnabled(arg);
      }
    }
  }

  private static final class CounterMaxLengthFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static CounterMaxLengthFunc8567756a instance = null;

    public static CounterMaxLengthFunc8567756a getInstance() {
      if(instance == null) {
        instance = new CounterMaxLengthFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof TextInputLayout) {
        ((TextInputLayout) v).setCounterMaxLength(arg);
      }
    }
  }

  private static final class ErrorFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    private static ErrorFuncc0af808b instance = null;

    public static ErrorFuncc0af808b getInstance() {
      if(instance == null) {
        instance = new ErrorFuncc0af808b();
      }
      return instance;
    }

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof TextInputLayout) {
        ((TextInputLayout) v).setError(arg);
      }
    }
  }

  private static final class ErrorEnabledFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    private static ErrorEnabledFunc148d6054 instance = null;

    public static ErrorEnabledFunc148d6054 getInstance() {
      if(instance == null) {
        instance = new ErrorEnabledFunc148d6054();
      }
      return instance;
    }

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof TextInputLayout) {
        ((TextInputLayout) v).setErrorEnabled(arg);
      }
    }
  }

  private static final class ExpandedFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    private static ExpandedFunc148d6054 instance = null;

    public static ExpandedFunc148d6054 getInstance() {
      if(instance == null) {
        instance = new ExpandedFunc148d6054();
      }
      return instance;
    }

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof AppBarLayout) {
        ((AppBarLayout) v).setExpanded(arg);
      }
    }
  }

  private static final class ExpandedTitleColorFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static ExpandedTitleColorFunc8567756a instance = null;

    public static ExpandedTitleColorFunc8567756a getInstance() {
      if(instance == null) {
        instance = new ExpandedTitleColorFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setExpandedTitleColor(arg);
      }
    }
  }

  private static final class ExpandedTitleGravityFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static ExpandedTitleGravityFunc8567756a instance = null;

    public static ExpandedTitleGravityFunc8567756a getInstance() {
      if(instance == null) {
        instance = new ExpandedTitleGravityFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setExpandedTitleGravity(arg);
      }
    }
  }

  private static final class ExpandedTitleMarginBottomFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static ExpandedTitleMarginBottomFunc8567756a instance = null;

    public static ExpandedTitleMarginBottomFunc8567756a getInstance() {
      if(instance == null) {
        instance = new ExpandedTitleMarginBottomFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setExpandedTitleMarginBottom(arg);
      }
    }
  }

  private static final class ExpandedTitleMarginEndFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static ExpandedTitleMarginEndFunc8567756a instance = null;

    public static ExpandedTitleMarginEndFunc8567756a getInstance() {
      if(instance == null) {
        instance = new ExpandedTitleMarginEndFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setExpandedTitleMarginEnd(arg);
      }
    }
  }

  private static final class ExpandedTitleMarginStartFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static ExpandedTitleMarginStartFunc8567756a instance = null;

    public static ExpandedTitleMarginStartFunc8567756a getInstance() {
      if(instance == null) {
        instance = new ExpandedTitleMarginStartFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setExpandedTitleMarginStart(arg);
      }
    }
  }

  private static final class ExpandedTitleMarginTopFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static ExpandedTitleMarginTopFunc8567756a instance = null;

    public static ExpandedTitleMarginTopFunc8567756a getInstance() {
      if(instance == null) {
        instance = new ExpandedTitleMarginTopFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setExpandedTitleMarginTop(arg);
      }
    }
  }

  private static final class ExpandedTitleTextAppearanceFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static ExpandedTitleTextAppearanceFunc8567756a instance = null;

    public static ExpandedTitleTextAppearanceFunc8567756a getInstance() {
      if(instance == null) {
        instance = new ExpandedTitleTextAppearanceFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setExpandedTitleTextAppearance(arg);
      }
    }
  }

  private static final class ExpandedTitleTypefaceFunc53b4afb implements Anvil.AttrFunc<Typeface> {
    private static ExpandedTitleTypefaceFunc53b4afb instance = null;

    public static ExpandedTitleTypefaceFunc53b4afb getInstance() {
      if(instance == null) {
        instance = new ExpandedTitleTypefaceFunc53b4afb();
      }
      return instance;
    }

    public void apply(View v, final Typeface arg, final Typeface old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setExpandedTitleTypeface(arg);
      }
    }
  }

  private static final class ForegroundFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    private static ForegroundFuncfb47464a instance = null;

    public static ForegroundFuncfb47464a getInstance() {
      if(instance == null) {
        instance = new ForegroundFuncfb47464a();
      }
      return instance;
    }

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ForegroundLinearLayout) {
        ((ForegroundLinearLayout) v).setForeground(arg);
      }
    }
  }

  private static final class ForegroundGravityFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static ForegroundGravityFunc8567756a instance = null;

    public static ForegroundGravityFunc8567756a getInstance() {
      if(instance == null) {
        instance = new ForegroundGravityFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ForegroundLinearLayout) {
        ((ForegroundLinearLayout) v).setForegroundGravity(arg);
      }
    }
  }

  private static final class HintFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    private static HintFuncc0af808b instance = null;

    public static HintFuncc0af808b getInstance() {
      if(instance == null) {
        instance = new HintFuncc0af808b();
      }
      return instance;
    }

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof TextInputLayout) {
        ((TextInputLayout) v).setHint(arg);
      }
    }
  }

  private static final class HintAnimationEnabledFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    private static HintAnimationEnabledFunc148d6054 instance = null;

    public static HintAnimationEnabledFunc148d6054 getInstance() {
      if(instance == null) {
        instance = new HintAnimationEnabledFunc148d6054();
      }
      return instance;
    }

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof TextInputLayout) {
        ((TextInputLayout) v).setHintAnimationEnabled(arg);
      }
    }
  }

  private static final class HintEnabledFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    private static HintEnabledFunc148d6054 instance = null;

    public static HintEnabledFunc148d6054 getInstance() {
      if(instance == null) {
        instance = new HintEnabledFunc148d6054();
      }
      return instance;
    }

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof TextInputLayout) {
        ((TextInputLayout) v).setHintEnabled(arg);
      }
    }
  }

  private static final class HintTextAppearanceFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static HintTextAppearanceFunc8567756a instance = null;

    public static HintTextAppearanceFunc8567756a getInstance() {
      if(instance == null) {
        instance = new HintTextAppearanceFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof TextInputLayout) {
        ((TextInputLayout) v).setHintTextAppearance(arg);
      }
    }
  }

  private static final class IconFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    private static IconFuncfb47464a instance = null;

    public static IconFuncfb47464a getInstance() {
      if(instance == null) {
        instance = new IconFuncfb47464a();
      }
      return instance;
    }

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof NavigationMenuItemView) {
        ((NavigationMenuItemView) v).setIcon(arg);
      }
    }
  }

  private static final class ItemBackgroundFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    private static ItemBackgroundFuncfb47464a instance = null;

    public static ItemBackgroundFuncfb47464a getInstance() {
      if(instance == null) {
        instance = new ItemBackgroundFuncfb47464a();
      }
      return instance;
    }

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof NavigationView) {
        ((NavigationView) v).setItemBackground(arg);
      }
    }
  }

  private static final class ItemBackgroundResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static ItemBackgroundResourceFunc8567756a instance = null;

    public static ItemBackgroundResourceFunc8567756a getInstance() {
      if(instance == null) {
        instance = new ItemBackgroundResourceFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof NavigationView) {
        ((NavigationView) v).setItemBackgroundResource(arg);
      }
    }
  }

  private static final class ItemIconTintListFunc9e5e0e4e implements Anvil.AttrFunc<ColorStateList> {
    private static ItemIconTintListFunc9e5e0e4e instance = null;

    public static ItemIconTintListFunc9e5e0e4e getInstance() {
      if(instance == null) {
        instance = new ItemIconTintListFunc9e5e0e4e();
      }
      return instance;
    }

    public void apply(View v, final ColorStateList arg, final ColorStateList old) {
      if (v instanceof NavigationView) {
        ((NavigationView) v).setItemIconTintList(arg);
      }
    }
  }

  private static final class ItemTextAppearanceFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static ItemTextAppearanceFunc8567756a instance = null;

    public static ItemTextAppearanceFunc8567756a getInstance() {
      if(instance == null) {
        instance = new ItemTextAppearanceFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof NavigationView) {
        ((NavigationView) v).setItemTextAppearance(arg);
      }
    }
  }

  private static final class ItemTextColorFunc9e5e0e4e implements Anvil.AttrFunc<ColorStateList> {
    private static ItemTextColorFunc9e5e0e4e instance = null;

    public static ItemTextColorFunc9e5e0e4e getInstance() {
      if(instance == null) {
        instance = new ItemTextColorFunc9e5e0e4e();
      }
      return instance;
    }

    public void apply(View v, final ColorStateList arg, final ColorStateList old) {
      if (v instanceof NavigationView) {
        ((NavigationView) v).setItemTextColor(arg);
      }
    }
  }

  private static final class NavigationItemSelectedListenerFunc80db0872 implements Anvil.AttrFunc<NavigationView.OnNavigationItemSelectedListener> {
    private static NavigationItemSelectedListenerFunc80db0872 instance = null;

    public static NavigationItemSelectedListenerFunc80db0872 getInstance() {
      if(instance == null) {
        instance = new NavigationItemSelectedListenerFunc80db0872();
      }
      return instance;
    }

    public void apply(View v, final NavigationView.OnNavigationItemSelectedListener arg, final NavigationView.OnNavigationItemSelectedListener old) {
      if (v instanceof NavigationView) {
        ((NavigationView) v).setNavigationItemSelectedListener(arg);
      }
    }
  }

  private static final class OnTabSelectedFuncaa1c085e implements Anvil.AttrFunc<TabLayout.OnTabSelectedListener> {
    private static OnTabSelectedFuncaa1c085e instance = null;

    public static OnTabSelectedFuncaa1c085e getInstance() {
      if(instance == null) {
        instance = new OnTabSelectedFuncaa1c085e();
      }
      return instance;
    }

    public void apply(View v, final TabLayout.OnTabSelectedListener arg, final TabLayout.OnTabSelectedListener old) {
      if (v instanceof TabLayout) {
        if (arg != null) {
          ((TabLayout) v).setOnTabSelectedListener(new TabLayout.OnTabSelectedListener() {
            public void onTabReselected(TabLayout.Tab a0) {
              arg.onTabReselected(a0);
              Anvil.render();
            }

            public void onTabSelected(TabLayout.Tab a0) {
              arg.onTabSelected(a0);
              Anvil.render();
            }

            public void onTabUnselected(TabLayout.Tab a0) {
              arg.onTabUnselected(a0);
              Anvil.render();
            }
          });
        } else {
          ((TabLayout) v).setOnTabSelectedListener((TabLayout.OnTabSelectedListener) null);
        }
      }
    }
  }

  private static final class RippleColorFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static RippleColorFunc8567756a instance = null;

    public static RippleColorFunc8567756a getInstance() {
      if(instance == null) {
        instance = new RippleColorFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof FloatingActionButton) {
        ((FloatingActionButton) v).setRippleColor(arg);
      }
    }
  }

  private static final class ScrimsShownFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    private static ScrimsShownFunc148d6054 instance = null;

    public static ScrimsShownFunc148d6054 getInstance() {
      if(instance == null) {
        instance = new ScrimsShownFunc148d6054();
      }
      return instance;
    }

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setScrimsShown(arg);
      }
    }
  }

  private static final class SelectedTabIndicatorColorFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static SelectedTabIndicatorColorFunc8567756a instance = null;

    public static SelectedTabIndicatorColorFunc8567756a getInstance() {
      if(instance == null) {
        instance = new SelectedTabIndicatorColorFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof TabLayout) {
        ((TabLayout) v).setSelectedTabIndicatorColor(arg);
      }
    }
  }

  private static final class SelectedTabIndicatorHeightFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static SelectedTabIndicatorHeightFunc8567756a instance = null;

    public static SelectedTabIndicatorHeightFunc8567756a getInstance() {
      if(instance == null) {
        instance = new SelectedTabIndicatorHeightFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof TabLayout) {
        ((TabLayout) v).setSelectedTabIndicatorHeight(arg);
      }
    }
  }

  private static final class StatusBarBackgroundFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    private static StatusBarBackgroundFuncfb47464a instance = null;

    public static StatusBarBackgroundFuncfb47464a getInstance() {
      if(instance == null) {
        instance = new StatusBarBackgroundFuncfb47464a();
      }
      return instance;
    }

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof CoordinatorLayout) {
        ((CoordinatorLayout) v).setStatusBarBackground(arg);
      }
    }
  }

  private static final class StatusBarBackgroundColorFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static StatusBarBackgroundColorFunc8567756a instance = null;

    public static StatusBarBackgroundColorFunc8567756a getInstance() {
      if(instance == null) {
        instance = new StatusBarBackgroundColorFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CoordinatorLayout) {
        ((CoordinatorLayout) v).setStatusBarBackgroundColor(arg);
      }
    }
  }

  private static final class StatusBarBackgroundResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static StatusBarBackgroundResourceFunc8567756a instance = null;

    public static StatusBarBackgroundResourceFunc8567756a getInstance() {
      if(instance == null) {
        instance = new StatusBarBackgroundResourceFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CoordinatorLayout) {
        ((CoordinatorLayout) v).setStatusBarBackgroundResource(arg);
      }
    }
  }

  private static final class StatusBarScrimFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    private static StatusBarScrimFuncfb47464a instance = null;

    public static StatusBarScrimFuncfb47464a getInstance() {
      if(instance == null) {
        instance = new StatusBarScrimFuncfb47464a();
      }
      return instance;
    }

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setStatusBarScrim(arg);
      }
    }
  }

  private static final class StatusBarScrimColorFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static StatusBarScrimColorFunc8567756a instance = null;

    public static StatusBarScrimColorFunc8567756a getInstance() {
      if(instance == null) {
        instance = new StatusBarScrimColorFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setStatusBarScrimColor(arg);
      }
    }
  }

  private static final class StatusBarScrimResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static StatusBarScrimResourceFunc8567756a instance = null;

    public static StatusBarScrimResourceFunc8567756a getInstance() {
      if(instance == null) {
        instance = new StatusBarScrimResourceFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setStatusBarScrimResource(arg);
      }
    }
  }

  private static final class TabGravityFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static TabGravityFunc8567756a instance = null;

    public static TabGravityFunc8567756a getInstance() {
      if(instance == null) {
        instance = new TabGravityFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof TabLayout) {
        ((TabLayout) v).setTabGravity(arg);
      }
    }
  }

  private static final class TabModeFunc8567756a implements Anvil.AttrFunc<Integer> {
    private static TabModeFunc8567756a instance = null;

    public static TabModeFunc8567756a getInstance() {
      if(instance == null) {
        instance = new TabModeFunc8567756a();
      }
      return instance;
    }

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof TabLayout) {
        ((TabLayout) v).setTabMode(arg);
      }
    }
  }

  private static final class TabTextColorsFunc9e5e0e4e implements Anvil.AttrFunc<ColorStateList> {
    private static TabTextColorsFunc9e5e0e4e instance = null;

    public static TabTextColorsFunc9e5e0e4e getInstance() {
      if(instance == null) {
        instance = new TabTextColorsFunc9e5e0e4e();
      }
      return instance;
    }

    public void apply(View v, final ColorStateList arg, final ColorStateList old) {
      if (v instanceof TabLayout) {
        ((TabLayout) v).setTabTextColors(arg);
      }
    }
  }

  private static final class TargetElevationFunce0893188 implements Anvil.AttrFunc<Float> {
    private static TargetElevationFunce0893188 instance = null;

    public static TargetElevationFunce0893188 getInstance() {
      if(instance == null) {
        instance = new TargetElevationFunce0893188();
      }
      return instance;
    }

    public void apply(View v, final Float arg, final Float old) {
      if (v instanceof AppBarLayout) {
        ((AppBarLayout) v).setTargetElevation(arg);
      }
    }
  }

  private static final class TextColorFunc9e5e0e4e implements Anvil.AttrFunc<ColorStateList> {
    private static TextColorFunc9e5e0e4e instance = null;

    public static TextColorFunc9e5e0e4e getInstance() {
      if(instance == null) {
        instance = new TextColorFunc9e5e0e4e();
      }
      return instance;
    }

    public void apply(View v, final ColorStateList arg, final ColorStateList old) {
      if (v instanceof NavigationMenuItemView) {
        ((NavigationMenuItemView) v).setTextColor(arg);
      }
    }
  }

  private static final class TitleFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    private static TitleFuncc0af808b instance = null;

    public static TitleFuncc0af808b getInstance() {
      if(instance == null) {
        instance = new TitleFuncc0af808b();
      }
      return instance;
    }

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof NavigationMenuItemView) {
        ((NavigationMenuItemView) v).setTitle(arg);
      }
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setTitle(arg);
      }
    }
  }

  private static final class TitleEnabledFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    private static TitleEnabledFunc148d6054 instance = null;

    public static TitleEnabledFunc148d6054 getInstance() {
      if(instance == null) {
        instance = new TitleEnabledFunc148d6054();
      }
      return instance;
    }

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof CollapsingToolbarLayout) {
        ((CollapsingToolbarLayout) v).setTitleEnabled(arg);
      }
    }
  }

  private static final class TypefaceFunc53b4afb implements Anvil.AttrFunc<Typeface> {
    private static TypefaceFunc53b4afb instance = null;

    public static TypefaceFunc53b4afb getInstance() {
      if(instance == null) {
        instance = new TypefaceFunc53b4afb();
      }
      return instance;
    }

    public void apply(View v, final Typeface arg, final Typeface old) {
      if (v instanceof TextInputLayout) {
        ((TextInputLayout) v).setTypeface(arg);
      }
    }
  }

  private static final class UpWithViewPagerFunc648eda47 implements Anvil.AttrFunc<ViewPager> {
    private static UpWithViewPagerFunc648eda47 instance = null;

    public static UpWithViewPagerFunc648eda47 getInstance() {
      if(instance == null) {
        instance = new UpWithViewPagerFunc648eda47();
      }
      return instance;
    }

    public void apply(View v, final ViewPager arg, final ViewPager old) {
      if (v instanceof TabLayout) {
        ((TabLayout) v).setupWithViewPager(arg);
      }
    }
  }

  private static final class UseCompatPaddingFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    private static UseCompatPaddingFunc148d6054 instance = null;

    public static UseCompatPaddingFunc148d6054 getInstance() {
      if(instance == null) {
        instance = new UseCompatPaddingFunc148d6054();
      }
      return instance;
    }

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof FloatingActionButton) {
        ((FloatingActionButton) v).setUseCompatPadding(arg);
      }
    }
  }
}
